
exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/periodos/add">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td><a href="/periodos/${slist[i].id}">
                    ${slist[i].id}
                    </a></td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/periodos/edit/${slist[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                    
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodPage = function( period, d ){
    pagHTML =`
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Periodo ${period.id}</h1>
                </header>
                <div class="w3-container">
                    <h1><b>Nome:</b> ${period.id}</h1>
                </div>
                <ul class="w3-ul w3-hoverable">
                    <li class="w3-padding-16">
                    `
    for(let i=0; i < period.compositores.length ; i++){
        pagHTML += `
                    <li class="w3-padding-16">
                        ${period.compositores[i]}
                    </li>
        `
    }
    pagHTML += `
                </ul>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.periodForm = function( d ){
    console.log("==================================")
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Novo Periodo</h1>
                </header>
                <form class="w3-container" action="/periodos" method="POST">
                    <label class="w3-text-teal"><b>Id</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="id">
                    <label class="w3-text-teal"><b>Nome</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="nome">
                    <label class="w3-text-teal"><b>Biografia</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="bio">
                    <label class="w3-text-teal"><b>Data de Nascimento</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="dataNasc">
                    <label class="w3-text-teal"><b>Data de Óbito</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="dataObito">
                    <label class="w3-text-teal"><b>Periodo</b></label>
                    <input class="w3-input w3-border w3-light-grey" type="text" name="periodo">
                    <input class="w3-btn w3-blue-grey" type="submit" value="Submit">
                </form>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.periodEditForm = function( period, d ){
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Periodo</title>
    </head>
    <form class = "w3-container" action="/periodos/edit/${period.id}" method="POST">
        <label class="w3-text-teal"><b>Id</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="id" value="${period.id}">
        <label class="w3-text-teal"><b>Nome</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="nome" value="${period.nome}">
        <label class="w3-text-teal"><b>Biografia</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="bio" value="${period.bio}">
        <label class="w3-text-teal"><b>Data de Nascimento</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="dataNasc" value="${period.dataNasc}">
        <label class="w3-text-teal"><b>Data de Óbito</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="dataObito" value="${period.dataObito}">
        <label class="w3-text-teal"><b>Periodo</b></label>
        <input class="w3-input w3-border w3-light-grey" type="text" name="periodo" value="${period.periodo}">
        <input class="w3-btn w3-blue-grey" type="submit" value="Submit">
    </form>
    <footer class="w3-container w3-blue">
        <h5>Generated by JoaoGDFaria in ${d}</h5>
    </footer>
    </html>
    `
}