
exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td><a href="/periodos/${slist[i].id}">
                    ${slist[i].id}
                    </a></td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/periodos/edit/${slist[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                    
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodPage = function( period, d ){
    pagHTML =`
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Periodo ${period.id}</h1>
                </header>
                <div class="w3-container">
                    <h1><b>Nome:</b> ${period.id}</h1>
                </div>
                <ul class="w3-ul w3-hoverable">
                    <li class="w3-padding-16">
                    `
    for(let i=0; i < period.compositores.length ; i++){
        pagHTML += `
                    <li class="w3-padding-16">
                        ${period.compositores[i]}
                    </li>
        `
    }
    pagHTML += `
                </ul>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}
