exports.mainPage = function(d){
    // Dois botões para redirecionar para as páginas de compositores e periodos
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Compositores</h1>
                </header>
                <div class="w3-container">
                    <p>HOME PAGE</p>
                </div>
                [<a class="w3-btn w3-round w3-teal" href="/compositores">Compositores</a>]
                [<a class="w3-btn w3-round w3-red" href="/periodos">Periodos</a>]
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
        `
}

exports.composersListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores
                    <a class="w3-btn w3-round w3-grey" href="/periodos">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th><th>Data Nascimento</th><th>Data Obito</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>    
                    <td>         
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].dataNasc}</td>
                    <td>${slist[i].dataObito}</td>
                    <td>${slist[i].periodo}</td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/compositores/edit/${slist[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodPage = function( period, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${period.id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${period.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${periodo.nome}</li>
                    `
        for(let i=0; i < period.compositores.length ; i++){
            var comp = period.compositores[i];
            pagHTML += `
                    <li><b>Compositor:</b> ${comp.nome}</li>
            `
        }
pagHTML += `
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por JoaoGDFaria ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td><a href="/periodos/${slist[i].id}">
                    ${slist[i].id}
                    </a></td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/periodos/edit/${slist[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                    
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composerCreatePage = function( composer, d ){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>bio</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>dataNasc</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>dataObito</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>periodo</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by JoaoGDFaria in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.composersFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>bio</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>dataNasc</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>dataObito</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                        <label>periodo</label>
                        <input class="w3-input w3-round" type="text" name="gitlink"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by JoaoGDFaria in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.studentFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composers Form</h2>
                </header>
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>id</label>
                    <input class="w3-input w3-round" type="text" name="id"/>
                    <label>nome</label>
                    <input class="w3-input w3-round" type="text" name="nome"/>
                    <label>bio</label>
                    <input class="w3-input w3-round" type="text" name="gitlink"/>
                    <label>dataNasc</label>
                    <input class="w3-input w3-round" type="text" name="gitlink"/>
                    <label>dataObito</label>
                    <input class="w3-input w3-round" type="text" name="gitlink"/>
                    <label>periodo</label>
                    <input class="w3-input w3-round" type="text" name="gitlink"/>
                </fieldset>
                <br/>
                <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
            </form>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by JoaoGDFaria in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.composerPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.nome}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Número: </b> ${compositor.id}</li>
                    <li><b>Data de nascimento</b> ${compositor.dataNasc}</li>
                    <li><b>Data de óbito</b> ${compositor.dataObito}</li>
                    <li><b>Periodo</b> ${compositor.periodo}</li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por JoaoGDFaria ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}